content/help/help.md

Encourage users to post questions in the Discourse rather than the Community Slack (use Slack more for synchronous, live events). Updated content and page metadata.
Also remove "Help" page header1 because it is redundant with headline title.

Replace help.md Community Slack with Discourse

---

src/components/data-ingestion-chart/data-ingestion-chart.tsx

A couple notes on the additions to `data-ingestion-chart.tsx`:
* On line 251, TypeScript requires that `chart.current` be checked for whether it's null. However, by my understanding, it should never actually be null, since this is happening in a `useEffect` callback which will only be called after the component has rendered and stored a value in `chart` via the `ref` attribute. Is there a better way to handle this than a `null` check?
* On line 37, a minimal type is declared to handle ECharts's graph parts, since the [echarts-for-react](https://github.com/hustcc/echarts-for-react) wrapper doesn't seem to provide types for the more internal aspects of ECharts

Add tooltip highlighting to data ingestion chart

---

content/home/publication-cloud.md

Added [Jasmine and Iris: population-scale structural variant comparison and analysis](https://doi.org/10.1038/s41592-022-01753-3) to the publications page

Added "Jasmine and Iris" paper #2505

---

next/package-lock.json
next/package.json

chore: bump findable ui package (data-explorer-ui) to 0.23.1 (#2736)

---

content/events/anvil2024-april-rtcd-workshop.md
content/site-map.yaml

feat: update rtcd (#2912)

---

gatsby-config.js

Removed `gatsby-plugin-catch-links`.

chore: removed gatsby-plugin-catch-links (#2927)

---

next/components/Home/components/Section/components/SectionHero/common/utils.ts

feat: added anvil 2024 community conference to home page carousel (#3112)

---

package-lock.json

`npm audit fix` appears to have resolved everything reported by NPM and Dependabot

chore: update packages to resolve vulnerabilities (#3205)

---

docs/news/2020/11/20/nhgri-anvil-now-supports-free-export-of-gtex-data.mdx
site-config/anvil-portal/dev/navigation/overview.ts

- Added a deprecation warning to https://anvilproject.org/news/2020/11/20/nhgri-anvil-now-supports-free-export-of-gtex-data
- Fixed a formatting error from an unrelated commit

chore: added deprecation warning to free gtex export article (#3259)

---

docs/team.mdx

Updated teams.mdx as follows:
- Remove "Gen3," from  "Members of these teams are also involved with platform and software development representing the Terra, Galaxy, Bioconductor, **Gen3,** and Dockstore teams."
- Remove references to Gen3 contributors from the University of Chicago as instructed by @NoopDog

fix: removed gen3 references from team.mdx (#3292 #3061)

---

docs/faq/resources-for-anvil-users.mdx

- Replaced the link to email [help@lists.anvilproject.org](mailto:help@lists.anvilproject.org) with a link to https://anvilproject.org/help

fix: removed email from resources-for-anvil-users.mdx (#3286)

---

docs/faq/resources-for-anvil-users.mdx

- Change link to help page from an external to internal link so it opens in the same tab

fix: changed help link to an internal link (#3302)

---

docs/learn/accessing-data/data-access-controls.mdx

Replaced a reference to Gen3 on [data-access-controls.mdx](https://anvilproject.org/learn/accessing-data/data-access-controls) with a reference to the AnVIL Data Explorer as specified in #3061

feat: replaced reference to gen3 on data-access-controls (#3309 #3061)

---

docs/learn/account-setup/overview-of-account-setup.mdx

Replaced and removed references to Gen3 on `overview-of-account-setup.mdx` as specified in #3061

content: removed references to gen3 on overview-of-account-setup (#3311 #3061)

---

docs/overview/security.mdx

Replaced references to gen3 on security.mdx as specified in #3061

content: replaced references to gen3 on security.mdx (#3313 #3061)

---

docs/learn/investigators/setting-up-lab-accounts.mdx

Replaced reference to Gen3 on setting-up-lab-accounts.mdx as specifed in #3061

feat: replaced references to gen3 on setting-up-lab-accounts (#3312 #3061)

---

docs/events/anvil2024-community-conference.mdx

Replace name of scientific lead per lead's request

fix: Update anvil2024-community-conference to update name of scientific lead for deep learning models CoFest

---

docs/learn/reference/gtex-v8-free-egress-instructions.mdx

Added a link to step-by-step instructions from Terra Support docs to access and export GTEx data to an AnVIL (Terra) workspace using DUOS.

content: add link to instructions for downloading GTEx data to AnVIL using DUOS

---

docs/news/2024/09/16/sunsetting-gen3-in-anvil.mdx

Added a link to a Terra Support article with step-by-step instructions for accessing and exporting GTEx data to a Terra workspace using DUOS. Note that until the export functionality in the Data Explorer is working, this is the preferred way for users to access GTEx data.

content: update sunsetting-gen3-in-anvil with link to data access via DUOS

---

scripts/set-version.sh

fix: append newline before other content in `set-version.sh` (#3387)

---

components/Home/components/Section/components/SectionDatasets/common/utils.ts
components/Home/components/Section/components/SectionDatasets/components/Datasets/components/Cards/cards.styles.ts
components/Home/components/Section/components/SectionDatasets/components/Datasets/components/Cards/cards.tsx
components/Home/components/Section/components/SectionDatasets/sectionDatasets.styles.ts
components/Home/components/Section/components/SectionDatasets/sectionDatasets.tsx
docs/consortia.mdx
docs/consortia/cser.mdx
docs/faq/resources-for-anvil-users.mdx
docs/faq/using-anvil.mdx
docs/learn/find-data.mdx
docs/learn/find-data/requesting-data-access.mdx
docs/news/2021/04/12/announcing-anvil-cloud-cost-credits-program.mdx
docs/news/2021/11/22/announcing-anvil-cloud-credits-continued-program.mdx
docs/news/2024/09/16/sunsetting-gen3-in-anvil.mdx
docs/overview.mdx
package-lock.json
package.json
pages/index.tsx
providers/sectionsData.ts
site-config/anvil-portal/dev/config.ts
views/HomeView/homeView.tsx

Closes #3564.
In the header:
- Removed "Catalog" link within "Datasets" menu,
- Moved "Explorer" link to first menu item,
- Added "Early Access Studies" link within "Datasets" menu with link to [DUOS](https://duos.broadinstitute.org/)
On the homepage:
- Removed arrow, link, and hover on the cards in the "Access diverse, open and controlled access, cloud-hosted datasets" section.
- Removed the "Explore Datasets" button.
Within the content:
- Removed any links to catalog, and replaced, where possible with links to the explorer (e.g. [current consortia](https://anvilproject.org/consortia#current-consortia)).

feat: replace catalog with early access studies link in header (#3564)

---

components/Home/components/Section/components/SectionHero/sectionHero.styles.ts
components/Home/components/Section/components/SectionHero/sectionHero.tsx

Closes #3562.
- Updated hero CTA with "Learn More", "Launch Terra" buttons, and text "AnVIL's cloud compute environment".
- Includes package.json update with latest `findable-ui` version.

feat: update hero ctas (#3562)

---

docs/consortia.mdx

content: add als compute consortium to the anvil consortium page (#3568)

---

docs/learn/find-data.mdx
site-config/anvil-portal/dev/config.ts

fix: update duos link to point directly to the anvil data library (#3603)

---

docs/learn/data-submitters/submission-guide/set-up-a-data-model.mdx

Noticed a typo (AnVI1) when presenting this page at an internal meeting, fixed to AnVIL!

content: fix typo in set-up-a-data-model.mdx

---

docs/learn/data-submitters/submission-guide/qc-data.mdx

Update portal doc to be a wrapper pointing to the current process in Terra Support.
This pull request updates the submission guide for data submitters, replacing the previous quality control (QC) process with a new data ingestion process. The changes reflect a shift in focus from QC to self-serve data ingestion into the AnVIL (Terra) Data Repository (TDR). The guide now provides detailed instructions for staging, ingesting, and cleaning up data.
* Updated the title and description to reflect the new focus on data ingestion instead of QC (`docs/learn/data-submitters/submission-guide/qc-data.mdx`).
* Replaced all references to QC workflows, metrics, and recommendations with instructions for staging data and ingesting it into TDR. This includes removing sections on QC guidance, metrics, and …

content: update qc-data.mdx with new data ingestion process

---

docs/learn/data-submitters/submission-guide/ingesting-data.mdx

Updating content as a wrapper that outlines steps and points to the most current documentation in Terra Support.
This pull request updates the submission guide for ingesting data into AnVIL to improve clarity, provide additional details, and restructure the step-by-step instructions. The most important changes include refining the process overview, adding new validation steps, and updating the language for consistency.
* Expanded the process overview into six detailed steps, including logging into AnVIL, setting up workspace cloud storage, uploading data object files, verifying file integrity via md5 hash, uploading TSV load files, and running a QC workflow for validation.
* Updated the instructions for logging into AnVIL to specify the use of a Google ID and the requirement for an …

content: update ingesting-data.mdx

---

docs/news/2025/08/25/all-of-us-anvil-imputation-service.mdx
docs/news/2025/09/25/all-of-us-anvil-imputation-service.mdx

#3667
This pull request adds a news article announcing the launch of the All of Us + AnVIL Imputation Service by the Broad Institute’s Data Sciences Platform. The article provides a brief overview and a link for more information.
- Documentation:
* Added a new news post in `docs/news/2025/08/25/all-of-us-anvil-imputation-service.mdx` announcing the All of Us + AnVIL Imputation Service and providing a link for further details.

content: added all of us + anvil imputation service news #3667

---

docs/news/2025/08/25/card-data-release-2.mdx

Closes #3672.
This pull request adds a new news post announcing the second release of long-read DNA sequencing data from the Center for Alzheimer's and Related Dementias (CARD) on the AnVIL platform. The post provides details on the datasets, access instructions, and the scientific context of the release.
New data release announcement:
* Added `card-data-release-2.mdx` to the `docs/news/2025/08/25/` directory, announcing the availability of CARD Data Release 2 on AnVIL, including dataset descriptions, access instructions, and scientific background.

content: added card data release to news #3672

---

components/Home/components/Section/components/SectionHero/common/utils.ts

Closes #3689.
This pull request adds a new carousel card to the homepage section, highlighting the launch of the All of Us + AnVIL Imputation Service by the Broad Institute's Data Sciences Platform.
Homepage content update:
* Added a new entry to the carousel in `buildCarouselCards` with information and a "Learn More" link about the All of Us + AnVIL Imputation Service.

content: added imputation service to carousel #3689
