- .circleci/config.yml
- .firebaserc
- .gitignore
- firebase.json
- package-lock.json
- package.json
This is just a template of the configuration file and it will need to be updated to reflect the setup for the site.
> Add the CircleCI template config file

- content/featured-workspaces/featured-workspaces.md
- src/styles/globalStyles.css
> Updated featured workspace text and added anvil branded terra link

- content/about/platform.md
Noticed this was misspelled in the section header.
> Fix typo in Dockstore spelling

- content/siteMap.yaml
- src/components/nav/nav.js
- src/components/nav/nav.module.css
- src/components/outline/outline.module.css
> Allow for a 2nd level of outline in the back page left nav. First pass. #213.

- content/ncpi/progress-updates/2020-04-16-ncpi-progress-update.md
- content/ncpi/training/2020-03-17-train-your-colleague.md
Updates:
- NCPI/training: 
-- added "NCPI Training" header
-- included paragraph introducing the "Train your colleague" workshop
-- reduced size of all headers by unit of one
- NCPI/Progress:
-- included first (OCT19) and second (APR20) NCPI workshop with agenda (and video links for APR20)
> Mo heydarian 27 jul

- content/help/help.md
> Add help links

- content/team/working-groups.md
Remove the very fluid Members lists and update chairs
> Update working group updates

- content/overview/data-consortia.md
Moving HPRC up from a planned consortium to a current consortium.
> Promote HPRC

- content/learn/data-submitters/data-approval-process.md
To see these in suggesting mode in a Google doc, go to https://docs.google.com/document/d/1_sB6Dfazkw54UqRR9Ac_A_XO-yrCcmWbwb-c1Y_MUoc/edit?usp=sharing
> Copyedits and formatting changes

- content/ncpi/training/training.md
Proposed updates to the Kids First training and support links.
> Kids First Updates

- content/learn/interactive-analysis/getting-started-with-bioconductor.md
I added recent workshops, two workspaces, and a resource. I also made small adjustments to the text for clarity.
> Add bioc anvil workshops

- content/events/agbt2022-advances-in-genome-biology-and-technology.md
https://twitter.com/mike_schatz/status/1482050234188455944
> agbt2022 postponed to June 6-9

- src/components/home/carousel/carousel-bullets/carousel-bullets.tsx
- src/components/home/carousel/carousel-slide/carousel-slide.module.css
- src/components/home/carousel/carousel-slide/carousel-slide.tsx
- src/components/home/carousel/carousel-slideshow/carousel-slideshow.tsx
- src/components/home/carousel/carousel.tsx
(Note: The interval for automatic rotation is set to a relatively low value of 5 seconds and may need to be adjusted)
> Add automatic rotation to homepage carousel (#1896)

- content/overview/overview.md
Misspelled registry the first time around 🤦🏻‍♀️
> Fix spelling 'registry' in overview.md

- .github/ISSUE_TEMPLATE/add-a-publication.md
Updated new publication issue template
> 2136 update publication issue template with all requied fields

- content/home/publication-cloud.md
- Added this paper to the publications page
- "Approaching complete genomes, transcriptomes and epi-omes with accurate long-read sequencing"
> Added "Approaching complete genomes, transcriptomes and epi-omes... #2471 

- content/events/anvil2023-february-office-hours.md
- content/site-map.yaml
Added the office hours event for February 2023
> Added February 2023 AnVIL Office Hours #2522

- content/events/anvil2023-march-demos.md
- content/events/anvil2023-may-demos.md
- content/events/gcc2023-galaxy-community-conference.md
- content/events/vadsti-2023.md
- content/site-map.yaml
* Added events for the March and May AnVIL Demos, Galaxy Community Conference 2023, and VADSTI 2023
* Altered the submitted "Event Details" section for the March demos to match the May demos
> Added March & May demos, GCC2023, & VADSTI 2023 #2601 #2602 #2603 #2604

- content/events/anvil2023-july-demos.md
- content/site-map.yaml
> feat: july anvil demos event (#2642)

- content/events/ashg2023-american-society-of-human-genetics.md
- content/site-map.yaml
> feat: ashg 2023 event (#2643)

- content/events/cshl-genome-informatics-2023.md
- content/site-map.yaml
> feat: cshl genome informatics 2023 (#2644)

- content/team/team.md
> feat: update nhgir members on the team page (#2667)

- content/ncpi/solicitation-announcements.md
> feat: update ncpi acc faq for 5/4 (#2669)

- content/site-map.yaml
- content/tos/anvil-explorer-tos.md
> feat: add terms of service (#2697)

- next/@types/global.d.ts
- next/pages/_app.tsx
- next/pages/consortia/cser.mdx
- next/site-config/anvil-portal/header.ts
Closes https://github.com/anvilproject/anvil-portal/issues/2709
> feat: add global types for images (#2709)

- next/package-lock.json
- next/package.json
> chore: bump data-explorer-ux package to v0.23.0 for cser ui updates (#2716)

- next/components/Consortia/CSER/components/ResearchMaterials/researchMaterials.styles.ts
- next/components/Consortia/CSER/components/ResearchMaterials/researchMaterials.tsx
- next/docs/common/constants.ts
- next/docs/consortia/cser/research-materials.mdx
> feat: create research materials stub (#2724)

- next/components/Consortia/CSER/components/MaterialsList/materialsList.styles.ts
- next/components/Consortia/CSER/components/MaterialsList/materialsList.tsx
- next/components/Consortia/CSER/components/ResearchMaterials/researchMaterials.tsx
- next/components/Consortia/CSER/components/Resources/resources.tsx
- next/components/Consortia/CSER/components/common/materials.ts
- next/docs/common/constants.ts
- next/docs/consortia/cser/resources.mdx
(I've copied the description from the existing page, but only the first accordion section, which is the one that contains files from the JSON, has been added)
> feat: add content to cser resources page (#2681)

- next/package-lock.json
- next/package.json
> chore: Update findable (data-explorer-ux) package to v0.24.0 (#2750)

- content/news/2023/05/09/data-management-anvil-hprc.md
- content/site-map.yaml
> feat: data management event news item (#2711)

- next/theme/common/components.ts
> feat: update paragraph theme (#2787)

- src/components/home/dataset-card/dataset-card.tsx
> feat: make homepage consortia links open in the same tab (#2661)

- content/faq/data-submission.md
Clarified "Who pays for storage costs in AnVIL?" question in the Data Submission FAQ
> chore: Clarified data submission faq (#2811)

- content/events/ashg2023-satisfying-nih-dms-requirements-with-anvil.md
- content/site-map.yaml
Added event page for "Satisfying NIH data management and sharing (DMS) requirements with AnVIL" to the events page
> chore: Added DMS requirements event page (#2812)

- content/home/mailing-list-cloud.md
Fixed typo regarding the mailing list on the home page
> chore: Fixed mailing list typo

- content/news/2019/12/05/dockstore-training.md
- content/news/2020/06/19/announcing-gen3-availability-in-anvil.md
- content/news/2022/05/03/announcing-anvil-cloud-credits-continued-program-awardees.md
- content/news/2022/08/10/scheduled-downtime-for-anvil-data-housing-workspaces.md
- content/news/2023/03/17/data-release-card-dementia-long-read-project.md
- content/news/2023/03/17/data-release-telomere-to-telomere.md
- content/news/2023/05/08/data-management-1000-genomes.md
- content/news/2023/05/09/data-management-anvil-hprc.md
- content/news/2023/09/05/data-release-als-compute-project.md
Added the date posted to all posts on the news page
> chore: added date posted to all news articles #2828

- content/events/anvil2023-september-demos.md
- content/site-map.yaml
> add september 2023 anvil demos (#2834)

- content/events/anvil2023-november-demos.md
- content/site-map.yaml
> add november 2023 anvil demo (#2836)

- content/events/anvil2023-december-demos.md
- content/site-map.yaml
> add december 2023 anvil demos (#2837)

- content/events/anvil2024-april-demos.md
- content/events/anvil2024-august-demos.md
- content/events/anvil2024-december-demos.md
- content/events/anvil2024-february-demos.md
- content/events/anvil2024-january-demos.md
- content/events/anvil2024-july-demos.md
- content/events/anvil2024-june-demos.md
- content/events/anvil2024-march-demos.md
- content/events/anvil2024-may-demos.md
- content/events/anvil2024-november-demos.md
- content/events/anvil2024-october-demos.md
- content/events/anvil2024-september-demos.md
- content/site-map.yaml
Added an events page for each AnVIL Demo scheduled during 2024
> chore: Add 2024 AnVIL demos

- content/team/team.md
> update team page content (#2864)

- content/team/team.md
> update team page link (#2872)

- content/events/anvil2024-advances-in-genome-biology-and-technology.md
- content/site-map.yaml
> advances in genome biology and technology (#2867)

- content/learn/data-submitters/consortium-data-access-guidelines.md
> feat: update consortium guidelines for anvil data access section consortium member responsibilities (#2879)

- content/home/tech-cloud.md
> feat: link to ncpi dataset catalog from anvil home page (#2883)

- content/team/working-groups.md
> feat: update working groups with new content (#2889)

- content/news/2024/02/02/downtime-for-anvil-data-storage.md
- content/site-map.yaml
Closes #2893.
Reviewers @frano-m
> feat: add news event scheduled downtime (#2894)

- src/utils/explore.service.js
Closes #2897.
Fixes PROD explore link.
> fix: explore link (#2897)

- next/components/Home/components/Section/components/SectionAnalysisPortals/common/utils.ts
Closes #2903.
Reviewers @frano-m.
> feat: update home page analysis portal text (#2903)

- next/docs/common/constants.ts
- next/docs/common/scope.ts
> feat: add portal url to mdx scope (#2907)

- next/docs/consortia/cser.mdx
Closes #2906.
Assignees @frano-m
> feat: add cser workspace to about page (#2906)

- content/news/2024/02/15/anvil-community-poll.md
- content/site-map.yaml
> feat: add community poll to news (#2919)

- next/docs/common/entities.ts
- next/docs/team.mdx
- next/docs/team/oversight-committee.mdx
- next/docs/team/working-groups.mdx
- next/site-config/anvil-portal/dev/navigation.ts
> feat: add team context to next (#2922)

- next/components/Home/components/Section/components/SectionAnalysisPortals/components/AnalysisPortals/analysisPortals.styles.ts
- next/components/Home/components/Section/components/SectionAnalysisPortals/components/AnalysisPortals/analysisPortals.tsx
- next/components/Home/components/Section/components/SectionAnalysisPortals/components/AnalysisPortals/common/constants.ts
- next/components/Home/components/Section/components/SectionAnalysisPortals/components/AnalysisPortals/hooks/useInteractivePortals.ts
- next/components/Home/components/Section/components/SectionAnalysisPortals/components/AnalysisPortals/hooks/useIntersectionObserver.ts
- next/components/Home/components/Section/components/SectionHero/components/Carousel/carousel.styles.ts
- next/components/Home/components/Section/components/SectionHero/components/Carousel/carousel.tsx
- next/components/Home/components/Section/components/SectionHero/components/Carousel/common/constants.ts
- next/components/Home/components/Section/components/SectionHero/components/Carousel/common/entities.ts
- next/components/Home/components/Section/components/SectionHero/components/Carousel/common/utils.ts
- next/components/Home/components/Section/components/SectionHero/components/Carousel/components/Arrow/arrow.styles.ts
- next/components/Home/components/Section/components/SectionHero/components/Carousel/components/Arrow/arrow.tsx
- next/components/Home/components/Section/components/SectionHero/components/Carousel/components/Cards/cards.styles.ts
- next/components/Home/components/Section/components/SectionHero/components/Carousel/components/Cards/cards.tsx
- next/components/Home/components/Section/components/SectionHero/components/Carousel/hooks/useInteractiveCarousel.ts
- next/components/Home/hooks/useSwipeInteraction/common/constants.ts
- next/components/Home/hooks/useSwipeInteraction/common/entities.ts
- next/components/Home/hooks/useSwipeInteraction/useSwipeInteraction.tsx
> feat: update home page analysis portals section to be interactive on smaller viewports (#2928)

- next/docs/common/entities.ts
- next/docs/privacy.mdx
- next/site-config/anvil-portal/dev/navigation.ts
> feat: fix privacy page (#2941)

- src/components/header/header.styles.ts
> fix: gatsby header height (#2952)

- next/docs/consortia.mdx
> feat: all consortia are listing a start and end date (#2965)

- next/docs/consortia.mdx
closes #2783.
assignees @frano-m.
> feat: update card consortia listing (#2783)

- next/docs/learn/accessing-data/bringing-your-own-data.mdx
- next/docs/learn/accessing-data/data-access-controls.mdx
- next/docs/learn/accessing-data/discovering-data.mdx
- next/docs/learn/accessing-data/requesting-data-access.mdx
- next/site-config/anvil-portal/dev/navigation.ts
> feat: add next content accessing data (#2974)

- next/docs/learn/analysis-workflows/running-galaxy-workflows-from-dockstore.mdx
- next/docs/learn/analysis-workflows/running-gatk.mdx
- next/docs/learn/analysis-workflows/using-example-workspaces.mdx
- next/site-config/anvil-portal/dev/navigation.ts
> feat: add next content running analysis workflows (#2975)

- next/docs/learn/anvil-mooc/cloud-computing.mdx
- next/docs/learn/anvil-mooc/cloud-costs.mdx
- next/docs/learn/anvil-mooc/use-case-eqtl.mdx
- next/docs/learn/anvil-mooc/use-case-gatk.mdx
- next/docs/learn/anvil-mooc/use-case-gwas.mdx
- next/docs/learn/anvil-mooc/what-is-anvil.mdx
- next/site-config/anvil-portal/dev/navigation.ts
> feat: add next content mooc (#2979)

- next/docs/learn/videos/anvil-videos.mdx
- next/docs/learn/videos/dockstore-videos.mdx
- next/docs/learn/videos/galaxy-videos.mdx
- next/docs/learn/videos/gen3-videos.mdx
- next/docs/learn/videos/seqr-videos.mdx
- next/docs/learn/videos/terra-videos.mdx
- next/site-config/anvil-portal/dev/navigation.ts
> feat: add next content video gallery (#2981)

- next/docs/learn/training/workshop-archive.mdx
- next/site-config/anvil-portal/dev/navigation.ts
> feat: add next content workshop archive (#2982)

- next/components/Home/components/Section/components/SectionUpdates/common/entities.ts
- next/components/Home/components/Section/components/SectionUpdates/common/utils.ts
- next/components/News/common/constants.ts
- next/components/News/common/utils.ts
- next/components/News/components/NewsHero/newsHero.tsx
- next/components/News/news.styles.ts
- next/components/News/news.tsx
- next/components/common/Link/link.tsx
- next/components/common/Typography/components/Heading/heading.tsx
- next/components/common/Video/video.styles.ts
- next/components/common/Video/video.tsx
- next/components/index.tsx
- next/content/constants.ts
- next/content/entities.ts
- next/content/utils.ts
- next/docs/common/constants.ts
- next/docs/common/entities.ts
- next/docs/common/utils.ts
- next/docs/consortia/cser/news.mdx
- next/docs/news.mdx
- next/docs/news/2019/12/05/dockstore-training.mdx
- next/docs/news/2020/05/21/discover-anvil-at-bcc-2020.mdx
- next/pages/[...slug].tsx
- next/pages/news/[year]/[month]/[date]/[slug].tsx
- next/pages/news/index.tsx
- next/plugins/common/utils.ts
- next/plugins/rehypeSlug.ts
- next/plugins/remarkHeadings.ts
- next/routes/constants.ts
- next/site-config/anvil-portal/dev/navigation.ts
> feat: create news page (#2963)

- content/team/team.md
> feat: fix typo on team page (#2988)

- content/news/2024/04/15/comparing-the-nhgri-anvil-platform.md
> feat: update comparing the nghri anvil platform (#3003)

- next/components/Consortia/consortia.styles.ts
- next/components/index.tsx
- next/docs/common/constants.ts
- next/docs/consortia.mdx
> feat: add t2t to consortia (#3015)

- next/pages/[...slug].tsx
> fix: 'conflicting paths returned from getstaticpaths' error (#3021)

- next/components/Events/common/constants.ts
- next/components/Events/common/utils.ts
- next/components/Events/components/EventsHero/eventsHero.styles.ts
- next/components/Events/components/EventsHero/eventsHero.tsx
- next/components/Events/events.styles.ts
- next/components/Events/events.tsx
- next/components/common/Typography/components/TextBodyLarge4002Lines/textBodyLarge4002Lines.tsx
- next/components/index.tsx
- next/content/entities.ts
- next/docs/common/constants.ts
- next/docs/common/entities.ts
- next/docs/events.mdx
- next/docs/events/agbt2022-advances-in-genome-biology-and-technology.mdx
- next/pages/[...slug].tsx
- next/pages/events/[slug].tsx
- next/pages/events/index.tsx
- next/routes/constants.ts
- next/site-config/anvil-portal/dev/navigation.ts
> feat: create events page (#3027)

- next/docs/common/entities.ts
- next/docs/help.mdx
- next/site-config/anvil-portal/dev/navigation.ts
> feat: add help context to next redo (#2940)

- next/components/common/Table/table.styles.ts
- next/components/common/Table/table.tsx
- next/docs/common/constants.ts
- next/docs/help.mdx
- next/docs/news.mdx
- next/docs/privacy.mdx
> feat: style help table (#3042)

- next/docs/privacy.mdx
> refactor: refactor privacy links (#3044)

- next/components/Layout/components/Content/content.styles.ts
- next/components/index.tsx
- next/docs/common/constants.ts
- next/docs/team.mdx
- next/docs/team/working-groups.mdx
> feat: style team pages (#3046)

- content/learn/data-submitters/data-submitters-overview.md
> feat: revert data submission guide (#3052)

- content/events/anvil2024-community-conference.md
- content/site-map.yaml
- next/docs/events/anvil2024-community-conference.mdx
> feat: event anvil community conference (#3059)

- content/events/anvil2024-introduction-fred-hutch-workshop.md
- content/site-map.yaml
- next/docs/events/anvil2024-introduction-fred-hutch-workshop.mdx
> feat: introduction to anvil at fred hutch workshop (#3057)

- content/events/anvil2024-community-conference.md
- content/events/anvil2024-introduction-fred-hutch-workshop.md
> feat: fix fred hutch event (#3068)

- next/docs/learn/accessing-data/data-access-controls.mdx
- next/docs/learn/accessing-data/requesting-data-access.mdx
- next/docs/learn/account-setup/obtaining-a-google-id.mdx
- next/docs/learn/billing-setup/billing-concepts.mdx
- next/docs/learn/data-submitters/submission-guide/prepare-for-submission.mdx
- next/docs/learn/investigators/setting-up-lab-accounts.mdx
> fix: linting and prepare for submission video (#3071)

- next/components/Home/common/entities.ts
- next/next.config.mjs
- next/package-lock.json
- next/package.json
- next/site-config/anvil-portal/dev/config.ts
- next/site-config/anvil-portal/dev/socialMedia.ts
> chore: update findable-ui to latest (#3080)

- next/docs/events/anvil2024-community-conference.mdx
> feat: update anvil community event speakers (#3083)

- next/docs/news.mdx
- next/docs/news/2024/04/15/comparing-the-nhgri-anvil-platform.mdx
> feat: update comparing-the-nhgri-anvil-platform (#3092)

- next/docs/events/anvil2024-community-conference.mdx
> feat: update anvil2024-community-conference (#3093)

- content/events/ashg2024-american-society-of-human-genetics.md
- content/site-map.yaml
- next/docs/events.mdx
- next/docs/events/ashg2024-american-society-of-human-genetics.mdx
> feat: add event ASHG 2024 (#3100)

- content/events/agbt2025-advances-in-genome-biology-and-technology.md
- content/site-map.yaml
- next/docs/events/agbt2025-advances-in-genome-biology-and-technology.mdx
> feat: add event agbt 2025 (#3102)

- content/events/cshl2024-biology-of-genomes.md
- content/site-map.yaml
- next/docs/events/cshl2024-biology-of-genomes.mdx
> feat: cshl biological data science meeting 2024 (#3099)

- next/docs/events/pag2025.mdx
> feat: pag 2025 (#3101)

- next/docs/consortia.mdx
> feat: update gregor consortia on consortia page (#3125)

- next/docs/news/2024/09/16/sunsetting-gen3-in-anvil.mdx
> feat: add news item for sunsetting gen3 (#3141)

- docs/news/2024/10/04/new-nih-data-managment-and-sharing-policy.mdx
Closes #3216.
Assginees @frano-m.
> feat: news Item - anvil helps researchers meet nih's new data management and sharing policy (#3216)

- docs/news/2024/10/04/nih-genomic-data-sharing-policy.mdx
> feat: news item - anvil helps researchers comply with the nih's updated genomic data sharing policy (#3215)

- docs/faq/data-security.mdx
Add a FAQ question to `/faq/data-security.mdx` as specified in #3285
> fix: added user account info FAQ item to data-security.mdx (#3285)

- docs/learn/data-submitters/submission-guide/set-up-a-data-model.mdx
Added direct link to the AnVILDataSubmissionFindabilitySubsetSchema.template.xlsx template with instructions on how to download.
> feat: add AnVILDataSubmissionFindabilitySubsetSchema.template.xlsx link to set-up-a-data-model

- docs/learn/accessing-data/requesting-data-access.mdx
Replaced reference to Gen3 as specified in #3061
> feat: replaced reference to gen3 on requesting-data-access(#3410 #3061)

- docs/news/2020/06/19/announcing-gen3-availability-in-anvil.mdx
- Added deprecation notice to Gen3 news article as specified in #3061
> feat: added deprecation notice to gen3 announcement (#3308 #3061)

- docs/news/2024/11/15/duos-announcement.mdx
- Added DUOS news page dated to Nov 15
> content: added duos news page (#3372)

- package-lock.json
- package.json
> chore: upgrade findable-ui to 15.0.0 (#3364)

- docs/news/2024/11/21/gregor-consortium.mdx
> feat: gregor release news article (#3385)

- components/Champions/champions.styles.ts
Resolves incorrect styles for #3283.
> fix: champions styles (#3283)

- components/Home/components/Section/components/SectionHero/common/utils.ts
- Added carousel card with a link to the [PRIMED study](https://www.cell.com/ajhg/fulltext/S0002-9297(24)00379-3)
> content: added PRIMED carousel card (#3402)

- docs/anvil-champions.mdx
> fix: minor capitalization fix in AnVIL Champions page

- docs/learn/investigators/setting-up-lab-accounts.mdx
> feat: apply strides pr text in the next site content (#3429)

- site-config/anvil-portal/dev/config.ts
- site-config/anvil-portal/dev/socialMedia.ts
- Added Linkedin to the socials footer
> content: added linkedin to socials (#3460)

- docs/events/anvil2025-january-demos.mdx
Closes https://github.com/anvilproject/anvil-portal/issues/3503.
> feat: jan 2025 demo event #3503

- docs/events/anvil2025-february-demos.mdx
> content: feb 2025 demo event #3504

- docs/events/anvil2025-march-demos.mdx
> content: add March 2025 demo event #3505

- docs/events/anvil2025-april-demos.mdx
> content: apr 2025 demo event #3506

- docs/events/anvil2025-may-demos.mdx
> content: may 2025 demo event #3507

- docs/events/anvil2025-june-demos.mdx
> content: june 2025 demo event #3508

- docs/events/anvil2025-july-demos.mdx
> content: jul 2025 demo event #3509

- docs/events/anvil2025-august-demos.mdx
> content: aug 2025 demo event #3510

- docs/events/anvil2025-september-demos.mdx
> content: sep 2025 demo event #3511

- docs/events/anvil2025-october-demos.mdx
> content: oct 2025 demo event #3512

- docs/learn/data-submitters/submission-guide/set-up-a-data-model.mdx
https://docs.google.com/document/d/1v-xtKiR08evO8yPnACn2cWc4blfdNcZecKQde5muFJU/edit?tab=t.0#heading=h.kci25c4eefij
> content: incremental updates to  set-up-a-data-model.mdx

- docs/events/ashg2025-american-society-of-human-genetics.mdx
> feat: add event ASHG 2025 (#3543)

- docs/events/cshl2025-biology-of-genomes.mdx
> feat: add event CSHL BoG 2025 (#3542)

- docs/events/gbcc2025-galaxy-and-bioconductor-community-conference.mdx
> feat: add event GBCC2025 (#3541)

- components/Home/components/Section/components/SectionAnalysisPortals/common/utils.ts
> content: update homepage card order to place anvil components on the top row (#3547)

- components/Home/components/Section/components/SectionAnalysisPortals/sectionAnalysisPortals.styles.ts
- components/Home/components/Section/components/SectionAnalysisPortals/sectionAnalysisPortals.tsx
Closes #3554.
As per [mock](https://www.figma.com/design/JOUDXkKfgivRNFdBsWDPEH/AnVIL?node-id=8380-3331&m=dev).
> content: add "Use your favorite platforms and tools" text to homepage (#3554)

- docs/learn/find-data/bringing-your-own-data.mdx
Added useful resources from Terra Support docs.
> content: add links to bringing-your-own-data.mdx

- components/Home/components/Section/components/SectionExplore/common/utils.ts
- components/Home/components/Section/components/SectionExplore/components/ToolsAndWorkflows/components/Card/card.styles.ts
- components/Home/components/Section/components/SectionExplore/components/ToolsAndWorkflows/components/Card/card.tsx
- components/Home/components/Section/components/SectionExplore/components/ToolsAndWorkflows/toolsAndWorkflows.styles.ts
- components/Home/components/Section/components/SectionExplore/components/ToolsAndWorkflows/toolsAndWorkflows.tsx
- components/Home/components/Section/components/SectionExplore/sectionExplore.styles.ts
- components/Home/components/Section/components/SectionExplore/sectionExplore.tsx
- pages/index.tsx
- providers/sectionsData.ts
- views/HomeView/homeView.tsx
> feat: add "explore" section to homepage (#3561)

- docs/consortia.mdx
> content: add international fetal genomics consortium to the anvil consortium page (#3569)

- analytics/anvil-analytics-portal/sheets/constants.py
- analytics/anvil-analytics-portal/sheets/generate_sheets_report.ipynb
- analytics/requirements.txt
Closes #3574 (see ticket for report link)
This also includes some simplifications using the features added in the latest analytics package version
> chore: add pageviews to analytics report (#3574)

- next.config.mjs
- package-lock.json
- package.json
> chore: update findable-ui to latest v22.0.0 (#3575)

- docs/learn/find-data/bringing-your-own-data.mdx
> content: fix spelling in bringing-your-own-data

- site-config/anvil-portal/dev/announcements/announcements.ts
- site-config/anvil-portal/prod/config.ts
> fix: fix prod announcement to show repository review banner (#3585)

- docs/news/2025/04/03/genomic-variant-analysis-vrs-annotator.mdx
> content: genomic variant analysis #3589

- docs/events/anvil2025-community-conference.mdx
> content: updated ACC 2025 dates #3610

- docs/events/anvil2025-community-conference.mdx
Would it be possible to fast track this update? Thank you!!
> content: Add registration links to anvil2025-community-conference.mdx

- docs/events/anvil2025-community-conference.mdx
- fixed virtual reg link
- fixed Day 2 date
> content: Fixes to anvil2025-community-conference.mdx

- docs/events/anvil2025-community-conference.mdx
@MillenniumFalconMechanic please disregard the last PR as it is out of date now.
> Update registration closed anvil2025-community-conference.mdx

- docs/events/anvil2025-community-conference.mdx
@MillenniumFalconMechanic will likely need your help formatting the agenda - I added rooms and some breaks so we can expand the cells to include talk titles plus session events. Please let me know if things get too jumbled and I'll share the reference I'm using. Thanks!!
> content: update agenda and add locations anvil2025-community-conference.mdx

- docs/news/2025/08/28/august-2025-data-release.mdx
Closes #3677 
This pull request adds a section to the August 2025 data release notes, highlighting recent developmental enhancements made to AnVIL data. These improvements address issues with data consistency and compatibility across different tools.
Developmental enhancements to AnVIL data:
* Resolved inconsistencies in snapshot naming conventions that were causing issues with indexing for the AnVIL Data Explorer.
* Standardized MD5 encoding for file metadata to Base64 to match GCS metadata.
* Corrected values that previously caused issues when importing data from DUOS or the AnVIL Data Explorer into Workspaces.
> fix: updated quarterly release content #3677
